### ISSUE TITLE
Is there any way to (optionally) search for Wednesday?

### ISSUE THREAD

**Issue by changelings** [mrozekma/gencon-hotel-check#12]
Thank you so much for this code! I know you can toggle things like the bed size you want as either/or, but is there any way to ask for both hotels with Wednesday available and without? I don't _need_ Wednesday, but I'd like it.

**Comment by mrozekma** [comment]
If you don't specify you want Wednesday (with `--wednesday` or similar), it will show hotels that have availability Thursday through Sunday regardless of if they have Wednesday or not. It doesn't block hotels that have availability Wednesday, it just doesn't consider it.

**Comment by changelings** [comment]
Thank you so much! I don't wanna start a new ticket, and I'm sorry for the silly questions, but... I'm seeing hotels that match my criteria and going to the housing portal right away, but they're not showing up no matter how I search, even though the script will continue saying it's available currently. It's happened a lot of times now—I don't imagine it's a problem with your software, I might just be misunderstanding the housing portal, as this is my first Gen Con. Would you happen to know anything how it works/if I'm missing something obvious? Your script is amazing either way and really appreciated :)

**Comment by mrozekma** [comment]
Hmm. If I search for connected hotels now I get 5 results, which matches what I see on the housing portal (plus a bunch farther out). Despite the hotels showing up in the portal search results, they do all say "Hotel is unavailable" on the right; is that what you're seeing? It looks like that happens because the hotels only have availability on Wednesday night and not the other days -- not sure why the portal chooses to show them in the results even when you have "show available only" checked. I'll look into how to filter those out

**Comment by changelings** [comment]
Hmm, I'm not sure. It always just shows me the same list of hotels, basically, the closest one being over 6 miles away. I had this same problem when I was trying to use genconhotels.com, so I don't imagine it's anything with your code, just something I'm misunderstanding with the website :) I'll leave it there though, don't wanna bother you about something that's not anything to do with your code!
